<?php

namespace AppBundle\Repository;

/**
 * CircuitProgrammeRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CircuitProgrammeRepository extends \Doctrine\ORM\EntityRepository
{
}
